spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_task_flow?createDatabaseIfNotExist=true
    password:
    username: root
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
server:
  port: 8082